version: "3.8"

services:
  certificate-server:
    image: vicn1708/certificate-server-fpt
    container_name: certificate-server
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - mongodb
    volumes:
      - ./env/env.server:/app/.env
    networks:
      - certificate-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ../backup-data/mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: certificateAdmin
      MONGO_INITDB_ROOT_PASSWORD: certificateAdmin
    command: [--auth]
    networks:
      - certificate-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/dhparam:/etc/ssl/certs
    depends_on:
      - certificate-server
    networks:
      - certificate-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - webserver
    networks:
      - certificate-network

networks:
  certificate-network:
    driver: bridge
